#!/usr/bin/env bash

set -o nounset
set -o errexit
set -o pipefail

POD_NAME=$(kubectl get pods -l app=docker-private-registry -n default |sed -e '1d'|awk '{print $1}') && kubectl port-forward ${POD_NAME} 5000:5000 -n default
